services:
  postgres-db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  production:
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: on-failure
    depends_on:
      - postgres-db
    environment:
      ConnectionStrings__DefaultConnection: ${DB_CONNECTION_STRING}
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "5176:80"

volumes:
  db_data: